version: '3.4'

services:

  compreface-api:
    image: ${registry}compreface-api:${API_VERSION}
    restart: always
    build:
      context: ../java
      dockerfile: ../dev/Dockerfile
      target: frs_core
      args:
        - ND4J_CLASSIFIER=${ND4J_CLASSIFIER}
    container_name: "compreface-api"
    ports:
      - "8082:8080"
      - "5005:5005"
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_URL=jdbc:postgresql://${postgres_domain}:${postgres_port}/${postgres_db}
      - SPRING_PROFILES_ACTIVE=dev
      - API_JAVA_OPTS=${compreface_api_java_options}
      - SAVE_IMAGES_TO_DB=${save_images_to_db}