apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: compreface-admin
  name: compreface-admin
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
    - name: "5006"
      port: 5006
      targetPort: 5005
  selector:
    io.kompose.service: compreface-admin
status:
  loadBalancer: {}
