apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: compreface-admin
  name: compreface-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: compreface-admin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: compreface-admin
    spec:
      containers:
        - env:
            - name: ADMIN_JAVA_OPTS
              value: -Xmx1g
            - name: EMAIL_FROM
              #value: sumitgupto@gmail.com
            - name: EMAIL_HOST
              value: smtp.gmail.com
            - name: EMAIL_PASSWORD
              #value: password
            - name: EMAIL_USERNAME
              #value: sumitgupto
            - name: ENABLE_EMAIL_SERVER
              value: "false"
            - name: MAX_FILE_SIZE
              value: 5MB
            - name: MAX_REQUEST_SIZE
              value: 10MB
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_URL
              value: jdbc:postgresql://compreface-postgres-db:6432/frs
            - name: POSTGRES_USER
              value: postgres
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          image: asia.gcr.io/test-facegate/compreface-admin:v1
          name: compreface-admin
          ports:
            - containerPort: 8080
            - containerPort: 5005
          resources: {}
      restartPolicy: Always
status: {}
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: compreface-admin
  name: compreface-admin
spec:
  type: NodePort
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
      nodePort: 30547
    - name: "5006"
      port: 5006
      targetPort: 5005
      nodePort: 32576
  selector:
    io.kompose.service: compreface-admin
status:
  loadBalancer: {}
