apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: compreface-api
  name: compreface-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: compreface-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: compreface-api
    spec:
      containers:
        - env:
            - name: API_JAVA_OPTS
              value: "-Xmx4g"
            - name: MAX_FILE_SIZE
              value: "5MB"
            - name: MAX_REQUEST_SIZE
              value: "10"
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_URL
              value: jdbc:postgresql://compreface-postgres-db:6432/frs
            - name: POSTGRES_USER
              value: postgres
            - name: SAVE_IMAGES_TO_DB
              value: "true"
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          image: asia.gcr.io/test-facegate/compreface-api:v1
          name: compreface-api
          ports:
            - containerPort: 8080
            - containerPort: 5005
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: compreface-api
  name: compreface-api
spec:
  type: NodePort
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8080
      nodePort: 31978
    - name: "5005"
      port: 5005
      targetPort: 5005
      nodePort: 30202
  selector:
    io.kompose.service: compreface-api
status:
  loadBalancer: {}
