version: '3.4'

volumes:
  postgres-data:

services:
  compreface-postgres-db:
    image: asia.gcr.io/test-facegate/compreface-postgres-db:v1
    restart: always
    container_name: "asia.gcr.io/test-facegacte/compreface-postgres-db"
    build: ../db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgres_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  compreface-admin:
    image: asia.gcr.io/test-facegate/compreface-admin:v1
    restart: always
    build:
      context: ../java
      dockerfile: ../dev/Dockerfile
      target: frs_crud
    container_name: "asia.gcr.io/test-facegacte/compreface-admin"
    ports:
      - "8081:8080"
      - "5006:5005"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_EMAIL_SERVER=${enable_email_server}
      - EMAIL_HOST=${email_host}
      - EMAIL_USERNAME=${email_username}
      - EMAIL_FROM=${email_from}
      - EMAIL_PASSWORD=${email_password}
      - ADMIN_JAVA_OPTS=${compreface_admin_java_options}
      - MAX_FILE_SIZE=${max_file_size}
      - MAX_REQUEST_SIZE=${max_request_size}B
    depends_on:
      - compreface-postgres-db
      - compreface-api

  compreface-api:
    image: asia.gcr.io/test-facegate/compreface-api:v1
    restart: always
    build:
      context: ../java
      dockerfile: ../dev/Dockerfile
      target: frs_core
      args:
        - ND4J_CLASSIFIER=${ND4J_CLASSIFIER}
    container_name: "asia.gcr.io/test-facegacte/compreface-api"
    ports:
      - "8082:8080"
      - "5005:5005"
    depends_on:
      - compreface-postgres-db
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_URL=jdbc:postgresql://${postgres_domain}:${postgres_port}/${postgres_db}
      - SPRING_PROFILES_ACTIVE=dev
      - API_JAVA_OPTS=${compreface_api_java_options}
      - SAVE_IMAGES_TO_DB=${save_images_to_db}
      - MAX_FILE_SIZE=${max_file_size}
      - MAX_REQUEST_SIZE=${max_request_size}B

  compreface-fe:
    image: asia.gcr.io/test-facegate/compreface-fe:v1
    restart: always
    build:
      context: ../ui
      dockerfile: docker-prod/Dockerfile
    container_name: "asia.gcr.io/test-facegacte/compreface-ui"
    ports:
      - "8000:80"
    depends_on:
      - compreface-api
      - compreface-admin
    environment:
      - CLIENT_MAX_BODY_SIZE=${max_request_size}

  compreface-core:
    image: asia.gcr.io/test-facegate/compreface-core:v1
    restart: always
    container_name: "asia.gcr.io/test-facegacte/compreface-core"
    ports:
      - "3300:3000"
    build:
      context: ../embedding-calculator
    environment:
      - ML_PORT=3000
