apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: compreface-postgres-db
  name: compreface-postgres-db
spec:
  ports:
    - name: "6432"
      port: 6432
      targetPort: 5432
  selector:
    io.kompose.service: compreface-postgres-db
status:
  loadBalancer: {}
