apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: compreface-postgres-db
data:
  POSTGRES_DB: frs
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: compreface-postgres-db
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: compreface-postgres-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compreface-postgres-db
  template:
    metadata:
      labels:
        app: compreface-postgres-db
    spec:
      containers:
        - name: compreface-postgres-db
          image: asia.gcr.io/test-facegate/compreface-postgres-db:v1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: compreface-postgres-db
spec:
  type: NodePort
  ports:
    - name: ports
      port: 6432
      targetPort: 5432
  selector:
    app: compreface-postgres-db